# Generated by Django 3.2.25 on 2024-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20240320_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
