# Generated by Django 3.2.25 on 2024-03-21 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='total_electricity_bill',
            new_name='total_rental_bill',
        ),
        migrations.AddField(
            model_name='electricity',
            name='total_electricity_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rent',
            name='month',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
